module.exports = {
    name: "XXXXXXXXX", // Enter your username here.
    pronouns: {
        pronouns1: "XXX", // Enter your pronouns here... (e.g. 'he')
        pronouns2: "XXX", // Enter your pronouns here... (e.g. 'him')
        pronouns3: "XXX" // Enter your pronouns here... (e.g. 'his')
    },
    picture: "XXXXXXXXX",  // Enter your profile picture here aswell...
    bio: "XXXXXXXXX",  // Enter your bio/about here...
    links: {
        youtube: "https://www.youtube.com/c/poonxal (Original creator.)", // Enter your YouTube channel URL here...
        twitch: "XXXXXXXXX", // Enter your Twitch username here...
        instagram: "None.", // Enter your Instagram URL here...
        instagram2: "None." // Enter your second Instagram URL here...
    }
}